# ============================================================================
# GITHUB ACTIONS WORKFLOW FOR CLOUD RUN DEPLOYMENT
# ============================================================================
# 
# INSTRUCTIONS:
# 1. Go to your GitHub repository: https://github.com/InfinityXOneSystems/lead-sniper
# 2. Navigate to: .github/workflows/
# 3. Create new file: deploy-cloud-run.yml
# 4. Copy the content below into that file
# 5. Commit directly to master branch
#
# REQUIRED SECRETS (Settings → Secrets and variables → Actions):
# - GCP_SA_KEY: Service account JSON key
# - GEMINI_API_KEY: Gemini API key
#
# ============================================================================

name: Deploy Lead Sniper to Cloud Run

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # 5 AM daily

env:
  PROJECT_ID: infinity-x-one-systems
  SERVICE_NAME: lead-sniper
  REGION: us-central1
  IMAGE: gcr.io/infinity-x-one-systems/lead-sniper

jobs:
  build-and-deploy:
    name: Build and Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
      
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker
      
      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE }}:${{ github.sha }} .
          docker tag ${{ env.IMAGE }}:${{ github.sha }} ${{ env.IMAGE }}:latest
      
      - name: Push Docker image to GCR
        run: |
          docker push ${{ env.IMAGE }}:${{ github.sha }}
          docker push ${{ env.IMAGE }}:latest
      
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }}:${{ github.sha }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 4Gi \
            --cpu 2 \
            --timeout 3600 \
            --concurrency 1 \
            --max-instances 10 \
            --set-env-vars "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" \
            --set-env-vars "GCP_SA_KEY=${{ secrets.GCP_SA_KEY }}" \
            --set-env-vars "PROJECT_ID=${{ env.PROJECT_ID }}" \
            --service-account infinity-x-one-systems@appspot.gserviceaccount.com
      
      - name: Setup Cloud Scheduler
        run: |
          # Get service URL
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format='value(status.url)')
          
          # Create or update Cloud Scheduler job for daily execution
          gcloud scheduler jobs create http lead-sniper-daily \
            --schedule="0 5 * * *" \
            --uri="${SERVICE_URL}/run" \
            --http-method=POST \
            --time-zone="America/New_York" \
            --location=${{ env.REGION }} \
            --attempt-deadline=3600s \
            || gcloud scheduler jobs update http lead-sniper-daily \
            --schedule="0 5 * * *" \
            --uri="${SERVICE_URL}/run" \
            --http-method=POST \
            --time-zone="America/New_York" \
            --location=${{ env.REGION }} \
            --attempt-deadline=3600s
      
      - name: Output deployment info
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region=${{ env.REGION }} --format='value(status.url)')
          echo "✅ Deployment complete!"
          echo "Service URL: ${SERVICE_URL}"
          echo "Scheduled execution: Daily at 5 AM EST"
